"""add trip.card_code column

Revision ID: 10a245145a5
Revises: 21f714cfa29f
Create Date: 2015-02-01 13:10:58.049000

"""

# revision identifiers, used by Alembic.
revision = '10a245145a5'
down_revision = '21f714cfa29f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('card_code', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'card_code')
    ### end Alembic commands ###
