"""add shape_paths table

Revision ID: 10d8e7a6ebe9
Revises: afbd0210643
Create Date: 2015-09-02 18:13:10.087884

"""

# revision identifiers, used by Alembic.
revision = '10d8e7a6ebe9'
down_revision = 'afbd0210643'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shape_paths',
    sa.Column('shape_id', sa.Integer(), nullable=False),
    sa.Column('shape_path', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('shape_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shape_paths')
    ### end Alembic commands ###
