"""Update agency col types

Revision ID: 1a6e215d57c2
Revises: 66991a0a75f
Create Date: 2018-06-28 09:30:58.881837

"""

# revision identifiers, used by Alembic.
revision = '1a6e215d57c2'
down_revision = '66991a0a75f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agency_version', 'agency_url',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agency_version', 'agency_url',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    ### end Alembic commands ###
