"""add tags table

Revision ID: 1ccf9b9d7a90
Revises: 12f1f4874373
Create Date: 2015-10-30 11:30:29.600664

"""

# revision identifiers, used by Alembic.
revision = '1ccf9b9d7a90'
down_revision = '12f1f4874373'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    ### end Alembic commands ###
