"""add stop_id constraint to stop_time

Revision ID: 2e6ca5e41d34
Revises: 42debc8b5637
Create Date: 2015-04-29 15:14:40.171351

"""

# revision identifiers, used by Alembic.
revision = '2e6ca5e41d34'
down_revision = '42debc8b5637'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'stop_times', 'stops', ['stop_id'], ['stop_id'],
    	onupdate="CASCADE", ondelete="CASCADE")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stop_times', type_='foreignkey')
    ### end Alembic commands ###
