"""finish migration

Revision ID: 33f1750e0376
Revises: 359f1dea5fff
Create Date: 2014-12-23 12:37:40.693015

"""

# revision identifiers, used by Alembic.
revision = '33f1750e0376'
down_revision = '359f1dea5fff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stops',
    sa.Column('stop_id', sa.String(length=50), nullable=False),
    sa.Column('stop_code', sa.String(length=50), nullable=True),
    sa.Column('stop_desc', sa.String(length=50), nullable=True),
    sa.Column('stop_name', sa.String(length=50), nullable=True),
    sa.Column('stop_lat', sa.Float(precision=53), nullable=True),
    sa.Column('stop_lon', sa.Float(precision=53), nullable=True),
    sa.Column('stop_calle', sa.String(length=50), nullable=True),
    sa.Column('stop_numero', sa.String(length=50), nullable=True),
    sa.Column('stop_entre', sa.String(length=50), nullable=True),
    sa.Column('stop_esquina', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_table('transfers',
    sa.Column('from_stop_id', sa.String(length=50), nullable=False),
    sa.Column('to_stop_id', sa.String(length=50), nullable=True),
    sa.Column('transfer_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('from_stop_id')
    )
    op.create_table('stop_seq',
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('stop_id', sa.String(length=50), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('stop_time', sa.String(length=50), nullable=True),
    sa.Column('shape_dist_traveled', sa.Float(precision=53), nullable=True),
    sa.PrimaryKeyConstraint('trip_id', 'stop_id', 'stop_sequence')
    )
    op.create_table('trips_start_times',
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('trip_id', 'service_id', 'start_time')
    )
    op.create_table('stop_times',
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('stop_id', sa.String(length=50), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.String(length=50), nullable=True),
    sa.Column('departure_time', sa.String(length=50), nullable=True),
    sa.Column('shape_dist_traveled', sa.Float(precision=53), nullable=True),
    sa.PrimaryKeyConstraint('trip_id', 'stop_id', 'stop_sequence')
    )
    op.create_table('shapes',
    sa.Column('shape_id', sa.String(length=50), nullable=False),
    sa.Column('shape_pt_lat', sa.Float(precision=53), nullable=True),
    sa.Column('shape_pt_lon', sa.Float(precision=53), nullable=True),
    sa.Column('shape_pt_time', sa.String(length=50), nullable=True),
    sa.Column('shape_pt_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('shape_id', 'shape_pt_sequence')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shapes')
    op.drop_table('stop_times')
    op.drop_table('trips_start_times')
    op.drop_table('stop_seq')
    op.drop_table('transfers')
    op.drop_table('stops')
    ### end Alembic commands ###
