"""add trip-calendardate-fareattribute-farerule-frecuency-routefrecuency

Revision ID: 359f1dea5fff
Revises: 868c59094b3
Create Date: 2014-12-22 10:42:01.641585

"""

# revision identifiers, used by Alembic.
revision = '359f1dea5fff'
down_revision = '868c59094b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fare_rules',
    sa.Column('fare_id', sa.String(length=50), nullable=False),
    sa.Column('route_id', sa.String(length=50), nullable=True),
    sa.Column('origin_id', sa.String(length=50), nullable=True),
    sa.Column('destination_id', sa.String(length=50), nullable=True),
    sa.Column('contains_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('fare_id')
    )
    op.create_table('fare_attributes',
    sa.Column('fare_id', sa.String(length=50), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('currency_type', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transfers', sa.String(length=50), nullable=True),
    sa.Column('transfer_duration', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('fare_id')
    )
    op.create_table('route_frequencies',
    sa.Column('route_id', sa.String(length=50), nullable=False),
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=False),
    sa.Column('headway_secs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('route_id', 'service_id', 'start_time', 'end_time')
    )
    op.create_table('trips',
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('route_id', sa.String(length=50), nullable=True),
    sa.Column('service_id', sa.String(length=50), nullable=True),
    sa.Column('trip_headsign', sa.String(length=150), nullable=True),
    sa.Column('trip_short_name', sa.String(length=150), nullable=True),
    sa.Column('direction_id', sa.String(length=50), nullable=True),
    sa.Column('shape_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['calendar.service_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_table('calendar_dates',
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('exception_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['calendar.service_id'], ),
    sa.PrimaryKeyConstraint('service_id', 'date', 'exception_type')
    )
    op.create_table('frequencies',
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=True),
    sa.Column('end_time', sa.String(length=50), nullable=True),
    sa.Column('headway_secs', sa.String(length=50), nullable=True),
    sa.Column('exact_times', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequencies')
    op.drop_table('calendar_dates')
    op.drop_table('trips')
    op.drop_table('route_frequencies')
    op.drop_table('fare_attributes')
    op.drop_table('fare_rules')
    ### end Alembic commands ###
