"""Allow longer stop names

Revision ID: 3800120c6be7
Revises: 522a0f4f96d5
Create Date: 2015-03-04 17:14:35.038340

"""

# revision identifiers, used by Alembic.
revision = '3800120c6be7'
down_revision = '522a0f4f96d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stops', 'stop_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stops', 'stop_name',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    ### end Alembic commands ###
