"""add service name column to calendar

Revision ID: 386dfd5b15c5
Revises: 3800120c6be7
Create Date: 2015-03-04 17:23:28.302259

"""

# revision identifiers, used by Alembic.
revision = '386dfd5b15c5'
down_revision = '3800120c6be7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('service_name', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar', 'service_name')
    ### end Alembic commands ###
