"""inital migration

Revision ID: 3b918dc47f3c
Revises: None
Create Date: 2015-03-06 17:13:24.436983

"""

# revision identifiers, used by Alembic.
revision = '3b918dc47f3c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fare_attributes',
    sa.Column('fare_id', sa.String(length=50), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('currency_type', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transfers', sa.String(length=50), nullable=True),
    sa.Column('transfer_duration', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('fare_id')
    )
    op.create_table('route_frequencies',
    sa.Column('route_id', sa.String(length=50), nullable=False),
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=False),
    sa.Column('headway_secs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('route_id', 'service_id', 'start_time', 'end_time')
    )
    op.create_table('trips_start_times',
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('trip_id', 'service_id', 'start_time')
    )
    op.create_table('stops',
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('stop_code', sa.String(length=50), nullable=True),
    sa.Column('stop_desc', sa.String(length=50), nullable=True),
    sa.Column('stop_name', sa.String(length=250), nullable=True),
    sa.Column('stop_lat', sa.Float(precision=53), nullable=True),
    sa.Column('stop_lon', sa.Float(precision=53), nullable=True),
    sa.Column('stop_calle', sa.String(length=50), nullable=True),
    sa.Column('stop_numero', sa.String(length=50), nullable=True),
    sa.Column('stop_entre', sa.String(length=50), nullable=True),
    sa.Column('stop_esquina', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_table('stop_times',
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.String(length=50), nullable=True),
    sa.Column('departure_time', sa.String(length=50), nullable=True),
    sa.Column('shape_dist_traveled', sa.Float(precision=53), nullable=True),
    sa.PrimaryKeyConstraint('trip_id', 'stop_id', 'stop_sequence')
    )
    op.create_table('fare_rules',
    sa.Column('fare_id', sa.String(length=50), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('origin_id', sa.String(length=50), nullable=True),
    sa.Column('destination_id', sa.String(length=50), nullable=True),
    sa.Column('contains_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('fare_id')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.String(length=50), nullable=True),
    sa.Column('route_short_name', sa.String(length=50), nullable=True),
    sa.Column('route_long_name', sa.String(length=150), nullable=True),
    sa.Column('route_desc', sa.String(length=150), nullable=True),
    sa.Column('route_type', sa.String(length=50), nullable=True),
    sa.Column('route_color', sa.String(length=50), nullable=True),
    sa.Column('route_text_color', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('shapes',
    sa.Column('shape_id', sa.String(length=50), nullable=False),
    sa.Column('shape_pt_lat', sa.Float(precision=53), nullable=True),
    sa.Column('shape_pt_lon', sa.Float(precision=53), nullable=True),
    sa.Column('shape_pt_time', sa.String(length=50), nullable=True),
    sa.Column('shape_pt_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('shape_id', 'shape_pt_sequence')
    )
    op.create_table('agency',
    sa.Column('agency_id', sa.String(length=50), nullable=False),
    sa.Column('agency_name', sa.String(length=50), nullable=True),
    sa.Column('agency_url', sa.String(length=50), nullable=True),
    sa.Column('agency_timezone', sa.String(length=50), nullable=True),
    sa.Column('agency_lang', sa.String(length=50), nullable=True),
    sa.Column('agency_phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('agency_id')
    )
    op.create_table('feed_info',
    sa.Column('feed_publisher_name', sa.String(length=50), nullable=False),
    sa.Column('feed_publisher_url', sa.String(length=50), nullable=True),
    sa.Column('feed_lang', sa.String(length=50), nullable=True),
    sa.Column('feed_version', sa.String(length=50), nullable=True),
    sa.Column('feed_start_date', sa.String(length=50), nullable=True),
    sa.Column('feed_end_date', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('feed_publisher_name')
    )
    op.create_table('calendar',
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('monday', sa.String(length=50), nullable=True),
    sa.Column('tuesday', sa.String(length=50), nullable=True),
    sa.Column('wednesday', sa.String(length=50), nullable=True),
    sa.Column('thursday', sa.String(length=50), nullable=True),
    sa.Column('friday', sa.String(length=50), nullable=True),
    sa.Column('saturday', sa.String(length=50), nullable=True),
    sa.Column('sunday', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('transfers',
    sa.Column('from_stop_id', sa.String(length=50), nullable=False),
    sa.Column('to_stop_id', sa.String(length=50), nullable=True),
    sa.Column('transfer_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('from_stop_id')
    )
    op.create_table('stop_seq',
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('stop_time', sa.String(length=50), nullable=True),
    sa.Column('shape_dist_traveled', sa.Float(precision=53), nullable=True),
    sa.PrimaryKeyConstraint('trip_id', 'stop_id', 'stop_sequence')
    )
    op.create_table('trips',
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.String(length=50), nullable=True),
    sa.Column('trip_headsign', sa.String(length=150), nullable=True),
    sa.Column('trip_short_name', sa.String(length=150), nullable=True),
    sa.Column('direction_id', sa.String(length=50), nullable=True),
    sa.Column('shape_id', sa.String(length=50), nullable=True),
    sa.Column('card_code', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['calendar.service_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_table('calendar_dates',
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('exception_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['calendar.service_id'], ),
    sa.PrimaryKeyConstraint('service_id', 'date', 'exception_type')
    )
    op.create_table('frequencies',
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=True),
    sa.Column('end_time', sa.String(length=50), nullable=True),
    sa.Column('headway_secs', sa.String(length=50), nullable=True),
    sa.Column('exact_times', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequencies')
    op.drop_table('calendar_dates')
    op.drop_table('trips')
    op.drop_table('stop_seq')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('calendar')
    op.drop_table('feed_info')
    op.drop_table('agency')
    op.drop_table('shapes')
    op.drop_table('routes')
    op.drop_table('fare_rules')
    op.drop_table('stop_times')
    op.drop_table('stops')
    op.drop_table('trips_start_times')
    op.drop_table('route_frequencies')
    op.drop_table('fare_attributes')
    ### end Alembic commands ###
