"""versioning route table

Revision ID: 3f5919056083
Revises: 10d8e7a6ebe9
Create Date: 2015-09-10 16:58:01.501882

"""

# revision identifiers, used by Alembic.
revision = '3f5919056083'
down_revision = '6fa0b4e158e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes_version',
                    sa.Column('route_id', sa.Integer(), autoincrement=False, nullable=False),
                    sa.Column('agency_id', sa.Integer(), autoincrement=False, nullable=True),
                    sa.Column('route_short_name', sa.String(length=50), autoincrement=False, nullable=True),
                    sa.Column('route_long_name', sa.String(length=150), autoincrement=False, nullable=True),
                    sa.Column('route_desc', sa.String(length=150), autoincrement=False, nullable=True),
                    sa.Column('route_type', sa.String(length=50), autoincrement=False, nullable=True),
                    sa.Column('route_color', sa.String(length=50), autoincrement=False, nullable=True),
                    sa.Column('build_type', sa.String(length=50), autoincrement=False, nullable=True),
                    sa.Column('route_text_color', sa.String(length=50), autoincrement=False, nullable=True),
                    sa.Column('active', sa.Boolean(), autoincrement=False, nullable=True),
                    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
                    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
                    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('route_id', 'transaction_id')
    )
    op.create_index(op.f('ix_routes_version_end_transaction_id'), 'routes_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_routes_version_operation_type'), 'routes_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_routes_version_transaction_id'), 'routes_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
                    sa.Column('issued_at', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('remote_addr', sa.String(length=50), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], [u'users.user_id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_routes_version_transaction_id'), table_name='routes_version')
    op.drop_index(op.f('ix_routes_version_operation_type'), table_name='routes_version')
    op.drop_index(op.f('ix_routes_version_end_transaction_id'), table_name='routes_version')
    op.drop_table('routes_version')
    ### end Alembic commands ###
