"""alter stop id columns to Integers

Revision ID: 4642a65cc52b
Revises: 386dfd5b15c5
Create Date: 2015-03-05 18:12:45.226561

"""

# revision identifiers, used by Alembic.
revision = '4642a65cc52b'
down_revision = '386dfd5b15c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stop_seq', 'stop_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stop_times', 'stop_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stops', 'stop_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stops', 'stop_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('stop_times', 'stop_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('stop_seq', 'stop_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    ### end Alembic commands ###
