"""alter stop id columns to Integers

Revision ID: 4642a65cc52b
Revises: 386dfd5b15c5
Create Date: 2015-03-05 18:12:45.226561

This migration cannot be run on a table containing string data in the stop_id
column. It must be run using the db command line and:

UPDATE stops SET stop_id = trim(both 'mM ' from stop_id);

UPDATE stop_seq SET stop_id = trim(both 'mM ' from stop_id);

UPDATE stop_times SET stop_id = trim(both 'mM ' from stop_id);

ALTER TABLE stops ALTER COLUMN stop_id TYPE INTEGER USING (trim(stop_id)::integer);

ALTER TABLE stop_seq ALTER COLUMN stop_id TYPE INTEGER USING (trim(stop_id)::integer);

ALTER TABLE stop_times ALTER COLUMN stop_id TYPE INTEGER USING (trim(stop_id)::integer);

"""

# revision identifiers, used by Alembic.
revision = '4642a65cc52b'
down_revision = '386dfd5b15c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stop_seq', 'stop_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stop_times', 'stop_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stops', 'stop_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stops', 'stop_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('stop_times', 'stop_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('stop_seq', 'stop_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    ### end Alembic commands ###
