"""add feed_info table

Revision ID: 4a003740b70b
Revises: 30ccb3e20ee2
Create Date: 2014-12-14 19:16:08.036585

"""

# revision identifiers, used by Alembic.
revision = '4a003740b70b'
down_revision = '30ccb3e20ee2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_info',
    sa.Column('feed_publisher_name', sa.String(length=50), nullable=False),
    sa.Column('feed_publisher_url', sa.String(length=50), nullable=True),
    sa.Column('feed_lang', sa.String(length=50), nullable=True),
    sa.Column('feed_version', sa.String(length=50), nullable=True),
    sa.Column('feed_start_date', sa.String(length=50), nullable=True),
    sa.Column('feed_end_date', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('feed_publisher_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_info')
    ### end Alembic commands ###
