"""add role_id to user model and init method defaults

Revision ID: 508f9a596a04
Revises: f0a5a9e564f
Create Date: 2015-05-03 20:01:38.536320

"""

# revision identifiers, used by Alembic.
revision = '508f9a596a04'
down_revision = 'f0a5a9e564f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    ### end Alembic commands ###
