"""add route build_type

Revision ID: 5104c2e527c3
Revises: 13136577df89
Create Date: 2015-04-18 15:40:16.201444

"""

# revision identifiers, used by Alembic.
revision = '5104c2e527c3'
down_revision = '13136577df89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('build_type', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'build_type')
    ### end Alembic commands ###
