"""change route.active to boolean

Revision ID: 522a0f4f96d5
Revises: 10a245145a5
Create Date: 2015-02-01 14:34:36.463536

"""

# revision identifiers, used by Alembic.
revision = '522a0f4f96d5'
down_revision = '10a245145a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'active')
    op.add_column('routes', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'active')
    op.add_column('routes', sa.Column('active', sa.String(length=50), nullable=True))
    ### end Alembic commands ###
