"""route.agency_id foreign key

Revision ID: afbd0210643
Revises: 4e1f43c86cf7
Create Date: 2015-07-31 18:43:06.647010

"""

# revision identifiers, used by Alembic.
revision = 'afbd0210643'
down_revision = '4e1f43c86cf7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'routes', 'agency', ['agency_id'], ['agency_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    ### end Alembic commands ###
