"""add route version tags

Revision ID: cddb5c3a054
Revises: 12f1f4874373
Create Date: 2015-10-29 17:28:56.046147

"""

# revision identifiers, used by Alembic.
revision = 'cddb5c3a054'
down_revision = '12f1f4874373'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agency_tag',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('agency_id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
        sa.ForeignKeyConstraint(['agency_id', 'transaction_id'],
            ['agency_version.agency_id', 'agency_version.transaction_id'], ),
        sa.PrimaryKeyConstraint('id', 'agency_id', 'transaction_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agency_tag')
    op.drop_table('tags')
    ### end Alembic commands ###
